#cloud-config

# Install security updates on Centos from IBM Cloud private mirror (no public access)
# SSH max sessions optimised for Ansible usage
# Minimal best practice SSH config    

runcmd:
  - touch /tmp/t 
  - chmod 777 /tmp/t 
  - touch /tmp/t1 
  - chmod 777 /tmp/t1  
  - yum install -y tar java > /tmp/t 
  - ps -eaf |grep -i firewall > /tmp/t1 2>&1
  - touch /tmp/t2
  - firewall-cmd --zone=public --permanent --add-service=http >> /tmp/t1 2>&1
  - touch /tmp/t3
  - firewall-cmd --zone=public --permanent --add-service=https >> /tmp/t1 2>&1
  - touch /tmp/t4
  - firewall-cmd --permanent --service=https --add-port=8080/tcp >> /tmp/t1 2>&1
  - touch /tmp/t5
  - firewall-cmd --reload >> /tmp/t1 2>&1
  - touch /tmp/t6
  - sudo systemctl restart firewalld >> /tmp/t1 2>&1
  - touch /tmp/t7
  - sudo systemctl status firewalld >> /tmp/t1 2>&1
  - touch /tmp/t8
  - sudo firewall-cmd --list-all --zone=public >>/tmp/t1 2>&1
  - touch /tmp/t9
